"""PR comment formatter — generates Markdown summaries for pull requests."""

from __future__ import annotations

from quant_scan.cicd.quality_gate import QualityGateResult
from quant_scan.core.models import ScanResult


def format_pr_comment(
    result: ScanResult,
    gate_result: QualityGateResult | None = None,
) -> str:
    """Generate a Markdown-formatted PR comment from scan results.

    Parameters
    ----------
    result:
        The scan result to summarize.
    gate_result:
        Optional quality gate result for pass/fail badge.
    """
    s = result.summary
    lines: list[str] = []

    # Header with badge
    if gate_result:
        badge = "PASSED" if gate_result.passed else "FAILED"
        lines.append(f"## Quant-Scan PQC Assessment: {badge}")
    else:
        lines.append("## Quant-Scan PQC Assessment")

    lines.append("")

    # Summary table
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Score | **{s.score}/100** (Grade {s.grade}) |")
    lines.append(f"| PQC Readiness | {s.pqc_readiness_pct}% |")
    lines.append(f"| Total Findings | {s.total_findings} |")
    lines.append(f"| Files Scanned | {s.files_scanned} |")
    lines.append(f"| Duration | {result.duration_seconds}s |")
    lines.append("")

    # Severity breakdown
    if s.by_severity:
        lines.append("### Severity Breakdown")
        lines.append("")
        for severity in ["critical", "high", "medium", "low", "info"]:
            count = s.by_severity.get(severity, 0)
            if count > 0:
                lines.append(f"- **{severity.upper()}**: {count}")
        lines.append("")

    # Quality gate reasons
    if gate_result and not gate_result.passed:
        lines.append("### Quality Gate Failures")
        lines.append("")
        for reason in gate_result.reasons:
            lines.append(f"- {reason}")
        lines.append("")

    # Top findings (first 5)
    if result.findings:
        lines.append("### Top Findings")
        lines.append("")
        for f in result.findings[:5]:
            lines.append(
                f"- `{f.rule_id}` ({f.severity.value}) "
                f"**{f.algorithm.name}** in `{f.location.file_path}:{f.location.line_number}` "
                f"— {f.message}"
            )
        if len(result.findings) > 5:
            lines.append(f"\n*...and {len(result.findings) - 5} more findings*")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [quant-scan](https://github.com/eyd-company/quant-scan)*")

    return "\n".join(lines)
